export declare const orderStateEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["CREATED", "PAYMENT_PENDING", "PAYMENT_AUTHORIZED", "PAYMENT_SETTLED", "SHIPPED", "DELIVERED", "CANCELLED"]>;
export declare const paymentStateEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["PENDING", "AUTHORIZED", "SETTLED", "DECLINED", "CANCELLED", "ERROR"]>;
export declare const assetTypeEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["IMAGE", "VIDEO", "DOCUMENT"]>;
export declare const bannerPositionEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["HERO", "DEALS", "DEALS_HORIZONTAL", "MIDDLE", "BOTTOM", "COLLECTION_TOP"]>;
export declare const adminRoleEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["SUPER_ADMIN", "ADMIN", "EDITOR"]>;
export declare const campaignStatusEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["DRAFT", "SCHEDULED", "ACTIVE", "COMPLETED", "PAUSED", "CANCELLED"]>;
export declare const campaignTypeEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["SEASONAL", "PROMOTIONAL", "PRODUCT_LAUNCH", "HOLIDAY", "LOYALTY", "RE_ENGAGEMENT", "OTHER"]>;
export declare const discountTypeEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["PERCENTAGE", "FIXED_AMOUNT", "FREE_SHIPPING", "BUY_X_GET_Y", "NONE"]>;
export declare const subscriberStatusEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["SUBSCRIBED", "UNSUBSCRIBED", "BOUNCED", "COMPLAINED"]>;
export declare const emailStatusEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["PENDING", "SENT", "OPENED", "CLICKED", "BOUNCED", "FAILED"]>;
export declare const automationTypeEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["ABANDONED_CHECKOUT", "ABANDONED_CART", "ABANDONED_BROWSE", "WELCOME_SUBSCRIBER", "POST_PURCHASE", "WIN_BACK", "BIRTHDAY", "PRODUCT_RECOMMENDATION"]>;
export declare const productConditionEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["NEW", "REFURBISHED"]>;
