import { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import { schema, banners } from '@workit/db';
export declare class BannersService {
    private db;
    constructor(db: PostgresJsDatabase<typeof schema>);
    createBanner(data: typeof banners.$inferInsert): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        enabled: boolean;
        title: string;
        sortOrder: number;
        position: "HERO" | "DEALS" | "DEALS_HORIZONTAL" | "MIDDLE" | "BOTTOM" | "COLLECTION_TOP";
        desktopImageId: string | null;
        mobileImageId: string | null;
        collectionId: string | null;
    }>;
    getBanners(): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        enabled: boolean;
        title: string;
        sortOrder: number;
        position: "HERO" | "DEALS" | "DEALS_HORIZONTAL" | "MIDDLE" | "BOTTOM" | "COLLECTION_TOP";
        desktopImageId: string | null;
        mobileImageId: string | null;
        collectionId: string | null;
        collection: {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            slug: string;
            enabled: boolean;
            assetId: string | null;
            sortOrder: number;
            parentId: string | null;
            showInMostShopped: boolean;
        } | null;
        desktopImage: {
            id: string;
            name: string;
            createdAt: Date;
            type: "IMAGE" | "VIDEO" | "DOCUMENT";
            mimeType: string;
            fileSize: number;
            source: string;
            preview: string;
            width: number | null;
            height: number | null;
        } | null;
        mobileImage: {
            id: string;
            name: string;
            createdAt: Date;
            type: "IMAGE" | "VIDEO" | "DOCUMENT";
            mimeType: string;
            fileSize: number;
            source: string;
            preview: string;
            width: number | null;
            height: number | null;
        } | null;
    }[]>;
    getBanner(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        enabled: boolean;
        title: string;
        sortOrder: number;
        position: "HERO" | "DEALS" | "DEALS_HORIZONTAL" | "MIDDLE" | "BOTTOM" | "COLLECTION_TOP";
        desktopImageId: string | null;
        mobileImageId: string | null;
        collectionId: string | null;
        collection: {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            slug: string;
            enabled: boolean;
            assetId: string | null;
            sortOrder: number;
            parentId: string | null;
            showInMostShopped: boolean;
        } | null;
        desktopImage: {
            id: string;
            name: string;
            createdAt: Date;
            type: "IMAGE" | "VIDEO" | "DOCUMENT";
            mimeType: string;
            fileSize: number;
            source: string;
            preview: string;
            width: number | null;
            height: number | null;
        } | null;
        mobileImage: {
            id: string;
            name: string;
            createdAt: Date;
            type: "IMAGE" | "VIDEO" | "DOCUMENT";
            mimeType: string;
            fileSize: number;
            source: string;
            preview: string;
            width: number | null;
            height: number | null;
        } | null;
    } | undefined>;
    updateBanner(id: string, data: Partial<typeof banners.$inferInsert>): Promise<{
        id: string;
        title: string;
        description: string | null;
        slug: string;
        position: "HERO" | "DEALS" | "DEALS_HORIZONTAL" | "MIDDLE" | "BOTTOM" | "COLLECTION_TOP";
        enabled: boolean;
        sortOrder: number;
        createdAt: Date;
        updatedAt: Date;
        desktopImageId: string | null;
        mobileImageId: string | null;
        collectionId: string | null;
    }>;
    deleteBanner(id: string): Promise<{
        success: boolean;
    }>;
    getBannersByPosition(position: string, enabled?: boolean): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        enabled: boolean;
        title: string;
        sortOrder: number;
        position: "HERO" | "DEALS" | "DEALS_HORIZONTAL" | "MIDDLE" | "BOTTOM" | "COLLECTION_TOP";
        desktopImageId: string | null;
        mobileImageId: string | null;
        collectionId: string | null;
        collection: {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            slug: string;
            enabled: boolean;
            assetId: string | null;
            sortOrder: number;
            parentId: string | null;
            showInMostShopped: boolean;
        } | null;
        desktopImage: {
            id: string;
            name: string;
            createdAt: Date;
            type: "IMAGE" | "VIDEO" | "DOCUMENT";
            mimeType: string;
            fileSize: number;
            source: string;
            preview: string;
            width: number | null;
            height: number | null;
        } | null;
        mobileImage: {
            id: string;
            name: string;
            createdAt: Date;
            type: "IMAGE" | "VIDEO" | "DOCUMENT";
            mimeType: string;
            fileSize: number;
            source: string;
            preview: string;
            width: number | null;
            height: number | null;
        } | null;
    }[]>;
}
