packages:
  - 'backend'
  - 'frontend'
  - 'admin'
  - 'packages/*'

overrides:
  unrs-resolver: 'npm:is-buffer@^2.0.5'

allowBuilds:
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
