import { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import { schema } from '@workit/db';
import type { CheckoutInput } from '@workit/validation';
export declare class OrderService {
    private db;
    constructor(db: PostgresJsDatabase<typeof schema>);
    private generateOrderCode;
    createOrder(customerId: string, input: CheckoutInput): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        customerId: string;
        code: string;
        shippingMethodId: string | null;
        state: "CREATED" | "PAYMENT_PENDING" | "PAYMENT_AUTHORIZED" | "PAYMENT_SETTLED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
        subTotal: number;
        shipping: number;
        tax: number;
        total: number;
        currencyCode: string;
        shippingAddressId: string | null;
        billingAddressId: string | null;
    }>;
    getOrder(id: string): Promise<{
        lines: {
            variant: {
                name: string;
                sku: string;
                product: {
                    name: string;
                };
            };
            id: string;
            productId: string;
            orderId: string;
            quantity: number;
            linePrice: number;
            product: {
                name: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                slug: string;
                deletedAt: Date | null;
                description: string | null;
                enabled: boolean;
                shippingMethodId: string | null;
                sku: string | null;
                salePrice: number | null;
                originalPrice: number | null;
                stockOnHand: number;
                condition: "NEW" | "REFURBISHED";
                brandId: string | null;
            };
        }[];
        id: string;
        createdAt: Date;
        updatedAt: Date;
        customerId: string;
        code: string;
        shippingMethodId: string | null;
        state: "CREATED" | "PAYMENT_PENDING" | "PAYMENT_AUTHORIZED" | "PAYMENT_SETTLED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
        subTotal: number;
        shipping: number;
        tax: number;
        total: number;
        currencyCode: string;
        shippingAddressId: string | null;
        billingAddressId: string | null;
        shippingAddress: {
            id: string;
            customerId: string | null;
            phoneNumber: string;
            fullName: string;
            streetLine1: string;
            streetLine2: string | null;
            city: string;
            province: string;
            postalCode: string;
            country: string;
            defaultShipping: boolean;
            defaultBilling: boolean;
        } | null;
        billingAddress: {
            id: string;
            customerId: string | null;
            phoneNumber: string;
            fullName: string;
            streetLine1: string;
            streetLine2: string | null;
            city: string;
            province: string;
            postalCode: string;
            country: string;
            defaultShipping: boolean;
            defaultBilling: boolean;
        } | null;
        customer: {
            name: string;
            id: string;
            email: string;
            emailVerified: boolean;
            image: string | null;
            createdAt: Date;
            updatedAt: Date;
            role: "ADMIN" | "CUSTOMER" | null;
            firstName: string | null;
            lastName: string | null;
        };
    }>;
    getCustomerOrders(customerId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        customerId: string;
        code: string;
        shippingMethodId: string | null;
        state: "CREATED" | "PAYMENT_PENDING" | "PAYMENT_AUTHORIZED" | "PAYMENT_SETTLED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
        subTotal: number;
        shipping: number;
        tax: number;
        total: number;
        currencyCode: string;
        shippingAddressId: string | null;
        billingAddressId: string | null;
    }[]>;
    findAll(): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        customerId: string;
        code: string;
        shippingMethodId: string | null;
        state: "CREATED" | "PAYMENT_PENDING" | "PAYMENT_AUTHORIZED" | "PAYMENT_SETTLED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
        subTotal: number;
        shipping: number;
        tax: number;
        total: number;
        currencyCode: string;
        shippingAddressId: string | null;
        billingAddressId: string | null;
        customer: {
            name: string;
            id: string;
            email: string;
            emailVerified: boolean;
            image: string | null;
            createdAt: Date;
            updatedAt: Date;
            role: "ADMIN" | "CUSTOMER" | null;
            firstName: string | null;
            lastName: string | null;
        };
    }[]>;
    updateOrderStatus(id: string, state: string): Promise<{
        id: string;
        code: string;
        customerId: string;
        state: "CREATED" | "PAYMENT_PENDING" | "PAYMENT_AUTHORIZED" | "PAYMENT_SETTLED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
        subTotal: number;
        shipping: number;
        tax: number;
        total: number;
        currencyCode: string;
        createdAt: Date;
        updatedAt: Date;
        shippingAddressId: string | null;
        billingAddressId: string | null;
        shippingMethodId: string | null;
    }>;
}
