import { CampaignsService } from './campaigns.service';
export declare class CampaignsController {
    private readonly campaignsService;
    constructor(campaignsService: CampaignsService);
    create(data: any): Promise<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        description: string | null;
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        revenue: number | null;
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdBy: string | null;
    }>;
    findAll(status?: string, type?: string, startDate?: string, endDate?: string): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }[]>;
    findActive(): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }[]>;
    findOne(id: string): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }>;
    findBySlug(slug: string): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }>;
    update(id: string, data: any): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }>;
    updateStats(id: string, stats: any): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }>;
    remove(id: string): Promise<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        description: string | null;
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        revenue: number | null;
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdBy: string | null;
    }>;
}
