import { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import * as schema from '@workit/db';
export declare class CampaignsService {
    private db;
    constructor(db: PostgresJsDatabase<typeof schema>);
    createCampaign(data: typeof schema.campaigns.$inferInsert): Promise<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        description: string | null;
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        revenue: number | null;
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdBy: string | null;
    }>;
    getCampaigns(filters?: {
        status?: string;
        type?: string;
        startDate?: Date;
        endDate?: Date;
    }): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }[]>;
    getCampaign(id: string): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }>;
    getCampaignBySlug(slug: string): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }>;
    updateCampaign(id: string, data: Partial<typeof schema.campaigns.$inferInsert>): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }>;
    deleteCampaign(id: string): Promise<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        description: string | null;
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        revenue: number | null;
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdBy: string | null;
    }>;
    getActiveCampaigns(): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }[]>;
    updateCampaignStats(id: string, stats: {
        emailsSent?: number;
        emailsOpened?: number;
        emailsClicked?: number;
        conversions?: number;
        revenue?: number;
    }): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        type: "SEASONAL" | "PROMOTIONAL" | "PRODUCT_LAUNCH" | "HOLIDAY" | "LOYALTY" | "RE_ENGAGEMENT" | "OTHER";
        status: "CANCELLED" | "DRAFT" | "SCHEDULED" | "ACTIVE" | "COMPLETED" | "PAUSED";
        startDate: Date;
        endDate: Date | null;
        targetAudience: string | null;
        discountType: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING" | "BUY_X_GET_Y" | "NONE" | null;
        discountValue: number | null;
        couponCode: string | null;
        minPurchaseAmount: number | null;
        maxDiscountAmount: number | null;
        usageLimit: number | null;
        usagePerCustomer: number | null;
        brevoEmailCampaignId: number | null;
        brevoListId: number | null;
        emailsSent: number | null;
        emailsOpened: number | null;
        emailsClicked: number | null;
        conversions: number | null;
        revenue: number | null;
        bannerIds: string | null;
        collectionIds: string | null;
        productIds: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdBy: string | null;
    }>;
}
