// Code generated by the Encore v1.54.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-mtn9w.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the mtn9w Encore application.
 */
export default class Client {
    public readonly assets: assets.ServiceClient
    public readonly brands: brands.ServiceClient
    public readonly collections: collections.ServiceClient
    public readonly products: products.ServiceClient
    public readonly orders: orders.ServiceClient
    public readonly shipping: shipping.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly customers: customers.ServiceClient
    public readonly users: users.ServiceClient
    public readonly analytics: analytics.ServiceClient
    public readonly banners: banners.ServiceClient
    public readonly blog: blog.ServiceClient
    public readonly campaigns: campaigns.ServiceClient
    public readonly homepage: homepage.ServiceClient
    public readonly settings: settings.ServiceClient
    public readonly store: store.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.assets = new assets.ServiceClient(base)
        this.brands = new brands.ServiceClient(base)
        this.collections = new collections.ServiceClient(base)
        this.products = new products.ServiceClient(base)
        this.orders = new orders.ServiceClient(base)
        this.shipping = new shipping.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.customers = new customers.ServiceClient(base)
        this.users = new users.ServiceClient(base)
        this.analytics = new analytics.ServiceClient(base)
        this.banners = new banners.ServiceClient(base)
        this.blog = new blog.ServiceClient(base)
        this.campaigns = new campaigns.ServiceClient(base)
        this.homepage = new homepage.ServiceClient(base)
        this.settings = new settings.ServiceClient(base)
        this.store = new store.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

export namespace assets {
    export interface Asset {
        id: string
        name: string
        source: string
        type: string
        size: number
        createdAt: string
        updatedAt: string
    }

    export interface AssetListResponse {
        assets: Asset[]
    }

    export interface CreateAssetInput {
        name: string
        source: string
        type: string
        size: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
        }

        /**
         * Create an asset record manually.
         */
        public async create(params: CreateAssetInput): Promise<Asset> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/assets`, JSON.stringify(params))
            return await resp.json() as Asset
        }

        /**
         * Get a single asset by ID.
         */
        public async get(id: string): Promise<Asset> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/assets/${encodeURIComponent(id)}`)
            return await resp.json() as Asset
        }

        /**
         * List assets with pagination.
         */
        public async list(params: {
    take?: number
    skip?: number
}): Promise<AssetListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                skip: params.skip === undefined ? undefined : String(params.skip),
                take: params.take === undefined ? undefined : String(params.take),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/assets`, undefined, {query})
            return await resp.json() as AssetListResponse
        }

        /**
         * Delete an asset and its file from the bucket.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/assets/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }
    }
}

export namespace brands {
    export interface Brand {
        id: string
        name: string
        slug: string
        enabled: boolean
        createdAt: string
        updatedAt: string
    }

    export interface BrandListResponse {
        brands: Brand[]
    }

    export interface CreateBrandInput {
        name: string
        slug: string
        enabled?: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Admin: Create a new brand.
         */
        public async create(params: CreateBrandInput): Promise<Brand> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/catalog/brands`, JSON.stringify(params))
            return await resp.json() as Brand
        }

        /**
         * Get a single brand by ID.
         */
        public async get(id: string): Promise<Brand> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/catalog/brands/${encodeURIComponent(id)}`)
            return await resp.json() as Brand
        }

        /**
         * List all brands.
         */
        public async list(): Promise<BrandListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/catalog/brands`)
            return await resp.json() as BrandListResponse
        }

        /**
         * Admin: Delete a brand.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/catalog/brands/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Admin: Update a brand.
         */
        public async update(id: string, params: {
    name?: string
    slug?: string
    enabled?: boolean
}): Promise<Brand> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/catalog/brands/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Brand
        }
    }
}

export namespace collections {
    export interface Collection {
        id: string
        name: string
        slug: string
        description: string | null
        enabled: boolean
        featured: boolean
        parentId: string | null
        assetId: string | null
        createdAt: string
        updatedAt: string
        asset?: any
        parent?: any
        children?: any[]
    }

    export interface CollectionListResponse {
        collections: Collection[]
    }

    export interface CreateCollectionInput {
        name: string
        slug: string
        description?: string
        enabled?: boolean
        featured?: boolean
        parentId?: string
        assetId?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.getBySlug = this.getBySlug.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Admin: Create a collection.
         */
        public async create(params: CreateCollectionInput): Promise<Collection> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/catalog/collections`, JSON.stringify(params))
            return await resp.json() as Collection
        }

        /**
         * Get a collection by ID.
         */
        public async get(id: string): Promise<Collection> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/catalog/collections/${encodeURIComponent(id)}`)
            return await resp.json() as Collection
        }

        /**
         * Get a collection by SLUG.
         */
        public async getBySlug(slug: string): Promise<Collection> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/catalog/collections/slug/${encodeURIComponent(slug)}`)
            return await resp.json() as Collection
        }

        /**
         * List collections with filters (e.g., featured, parentId).
         */
        public async list(params: {
    featured?: boolean
    parentId?: string | null
}): Promise<CollectionListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                featured: params.featured === undefined ? undefined : String(params.featured),
                parentId: params.parentId === undefined ? undefined : String(params.parentId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/catalog/collections`, undefined, {query})
            return await resp.json() as CollectionListResponse
        }

        /**
         * Admin: Delete a collection.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/catalog/collections/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Admin: Update a collection.
         */
        public async update(id: string, params: {
    name?: string
    slug?: string
    description?: string
    enabled?: boolean
    featured?: boolean
    parentId?: string
    assetId?: string
}): Promise<Collection> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/catalog/collections/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Collection
        }
    }
}

export namespace products {
    export interface CreateProductInput {
        name: string
        slug: string
        description?: string
        sku: string
        salePrice: number
        originalPrice: number
        stockOnHand: number
        enabled?: boolean
        collections?: string[]
        homepageCollections?: string[]
        assetIds?: string[]
    }

    export interface Product {
        id: string
        name: string
        slug: string
        description: string | null
        sku: string
        salePrice: number
        originalPrice: number
        stockOnHand: number
        enabled: boolean
        createdAt: string
        updatedAt: string
        assets?: any[]
        collections?: any[]
    }

    export interface ProductListResponse {
        products: Product[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.search = this.search.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Admin: Create a product with its relations.
         */
        public async create(params: CreateProductInput): Promise<Product> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/catalog/products`, JSON.stringify(params))
            return await resp.json() as Product
        }

        /**
         * Get a single product by ID.
         */
        public async get(id: string): Promise<Product> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/catalog/products/${encodeURIComponent(id)}`)
            return await resp.json() as Product
        }

        /**
         * List products with pagination.
         */
        public async list(params: {
    limit?: number
    offset?: number
    collectionId?: string
}): Promise<ProductListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                collectionId: params.collectionId,
                limit:        params.limit === undefined ? undefined : String(params.limit),
                offset:       params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/catalog/products`, undefined, {query})
            return await resp.json() as ProductListResponse
        }

        /**
         * Admin: Delete a product.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/catalog/products/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Search products by name, description, or SKU.
         */
        public async search(params: {
    q: string
}): Promise<ProductListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                q: params.q,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/catalog/products/search`, undefined, {query})
            return await resp.json() as ProductListResponse
        }

        /**
         * Admin: Update a product and its relations.
         */
        public async update(id: string, params: {
    name?: string
    slug?: string
    description?: string
    sku?: string
    salePrice?: number
    originalPrice?: number
    stockOnHand?: number
    enabled?: boolean
    collections?: string[]
    homepageCollections?: string[]
    assetIds?: string[]
}): Promise<Product> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/catalog/products/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Product
        }
    }
}

export namespace orders {
    export interface AddressData {
        id: string
        fullName: string
        streetLine1: string
        city: string
        country: string
    }

    export interface AddressInput {
        firstName: string
        lastName: string
        streetLine1: string
        streetLine2?: string
        city: string
        province?: string
        postalCode?: string
        country?: string
        phoneNumber?: string
    }

    export interface CheckoutInput {
        items: OrderItem[]
        customerEmail: string
        customerName: string
        customerId?: string
        shippingAddress: AddressInput
        billingAddress?: AddressInput
        shippingMethodId: string
        shippingCost?: number
    }

    export interface CheckoutResponse {
        orderId: string
        orderCode: string
        total: number
        customerId: string
    }

    export interface Order {
        id: string
        code: string
        customerId: string
        shippingAddressId: string | null
        billingAddressId: string | null
        shippingMethodId: string | null
        subTotal: number
        shipping: number
        tax: number
        total: number
        state: string
        currencyCode: string
        createdAt: string
        updatedAt: string
        customer?: UserData | null
        lines?: OrderLine[] | null
        payments?: PaymentData[] | null
        shippingAddress?: AddressData | null
        billingAddress?: AddressData | null
    }

    export interface OrderItem {
        productId: string
        quantity: number
        salePrice?: number
        originalPrice?: number
    }

    export interface OrderLine {
        id: string
        productId: string
        quantity: number
        linePrice: number
        product?: any
    }

    export interface OrderListResponse {
        orders: Order[]
    }

    export interface PaymentData {
        id: string
        amount: number
        method: string
        state: string
        transactionId?: string | null
    }

    export interface PaymentVerificationResponse {
        success: boolean
        orderCode: string
    }

    export interface UserData {
        id: string
        email: string
        name: string
        role: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.getByEmail = this.getByEmail.bind(this)
            this.list = this.list.bind(this)
            this.listMyOrders = this.listMyOrders.bind(this)
            this.updateStatus = this.updateStatus.bind(this)
            this.verifyPayment = this.verifyPayment.bind(this)
        }

        /**
         * Public: Create order from checkout.
         */
        public async create(params: CheckoutInput): Promise<CheckoutResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/orders/checkout`, JSON.stringify(params))
            return await resp.json() as CheckoutResponse
        }

        /**
         * Authenticated: Get single order details.
         */
        public async get(id: string): Promise<Order> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/orders/${encodeURIComponent(id)}`)
            return await resp.json() as Order
        }

        /**
         * Public: Get orders by customer email (Internal use).
         */
        public async getByEmail(email: string): Promise<OrderListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/orders/by-email/${encodeURIComponent(email)}`)
            return await resp.json() as OrderListResponse
        }

        /**
         * Admin: List all orders.
         */
        public async list(): Promise<OrderListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/orders`)
            return await resp.json() as OrderListResponse
        }

        /**
         * User: Get my orders.
         */
        public async listMyOrders(): Promise<OrderListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/orders/me`)
            return await resp.json() as OrderListResponse
        }

        /**
         * Admin: Update order status.
         */
        public async updateStatus(id: string, params: {
    state: string
}): Promise<Order> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/orders/${encodeURIComponent(id)}/status`, JSON.stringify(params))
            return await resp.json() as Order
        }

        /**
         * Public: Verify payment and update order status.
         */
        public async verifyPayment(params: {
    orderId: string
    reference: string
    amount: number
    status: string
    provider: string
}): Promise<PaymentVerificationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/orders/verify-payment`, JSON.stringify(params))
            return await resp.json() as PaymentVerificationResponse
        }
    }
}

export namespace shipping {
    export interface CreateZoneInput {
        shippingMethodId: string
        county: string
        cities?: {
            cityTown: string
            standardPrice: number
            expressPrice: number
        }[]
    }

    export interface ShippingCity {
        id: string
        zoneId: string
        cityTown: string
        standardPrice: number
        expressPrice: number
        createdAt: string
        updatedAt: string
    }

    export interface ShippingMethod {
        id: string
        name: string
        description: string | null
        enabled: boolean
        createdAt: string
        updatedAt: string
        zones?: ShippingZone[]
    }

    export interface ShippingMethodListResponse {
        methods: ShippingMethod[]
    }

    export interface ShippingZone {
        id: string
        shippingMethodId: string
        county: string
        createdAt: string
        updatedAt: string
        cities?: ShippingCity[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createZone = this.createZone.bind(this)
            this.deleteZone = this.deleteZone.bind(this)
            this.listMethods = this.listMethods.bind(this)
            this.updateZone = this.updateZone.bind(this)
        }

        /**
         * Admin: Create a new shipping zone.
         */
        public async createZone(params: CreateZoneInput): Promise<ShippingZone> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/logistics/shipping-zones`, JSON.stringify(params))
            return await resp.json() as ShippingZone
        }

        /**
         * Admin: Delete a shipping zone.
         */
        public async deleteZone(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/logistics/shipping-zones/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * List all shipping methods with enriched zones and cities.
         */
        public async listMethods(): Promise<ShippingMethodListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/logistics/shipping-methods`)
            return await resp.json() as ShippingMethodListResponse
        }

        /**
         * Admin: Update a shipping zone.
         */
        public async updateZone(id: string, params: {
    shippingMethodId?: string
    county?: string
    cities?: {
        cityTown: string
        standardPrice: number
        expressPrice: number
    }[]
}): Promise<ShippingZone> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/logistics/shipping-zones/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as ShippingZone
        }
    }
}

export namespace auth {
    export interface AuthResponse {
        success: boolean
        token?: string
        user?: UserData
        error?: string
    }

    export interface LoginParams {
        email: string
        password: string
    }

    export interface RegisterParams {
        email: string
        password: string
        name?: string
        firstName: string
        lastName: string
        role?: string
    }

    export interface UserData {
        id: string
        email: string
        name: string
        role: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.handleAuth = this.handleAuth.bind(this)
            this.login = this.login.bind(this)
            this.register = this.register.bind(this)
        }

        /**
         * Handle Better Auth requests by proxying to the Better Auth Node.js handler.
         */
        public async handleAuth(method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE" | "HEAD" | "OPTIONS" | "TRACE", path: string[], body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/auth/${path.map(encodeURIComponent).join("/")}`, body, options)
        }

        /**
         * Legacy/Alternative Login wrapper.
         */
        public async login(params: LoginParams): Promise<AuthResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/login`, JSON.stringify(params))
            return await resp.json() as AuthResponse
        }

        /**
         * Legacy/Alternative Register wrapper (can be used if needed).
         */
        public async register(params: RegisterParams): Promise<AuthResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/register`, JSON.stringify(params))
            return await resp.json() as AuthResponse
        }
    }
}

export namespace customers {
    export interface CreateCustomerInput {
        email: string
        name: string
        firstName?: string
        lastName?: string
    }

    export interface Customer {
        id: string
        email: string
        name: string
        firstName: string | null
        lastName: string | null
        role: string
        createdAt: string
        updatedAt: string
        addresses?: any[]
        orders?: any[]
    }

    export interface CustomerListResponse {
        customers: Customer[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Admin: Create a new customer.
         */
        public async create(params: CreateCustomerInput): Promise<Customer> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/identity/customers`, JSON.stringify(params))
            return await resp.json() as Customer
        }

        /**
         * Get a single customer by ID.
         */
        public async get(id: string): Promise<Customer> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/identity/customers/${encodeURIComponent(id)}`)
            return await resp.json() as Customer
        }

        /**
         * List all customers (users with non-ADMIN roles).
         */
        public async list(): Promise<CustomerListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/identity/customers`)
            return await resp.json() as CustomerListResponse
        }

        /**
         * Admin: Delete a customer.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/identity/customers/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Admin: Update a customer.
         */
        public async update(id: string, params: {
    email?: string
    name?: string
    firstName?: string
    lastName?: string
}): Promise<Customer> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/identity/customers/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Customer
        }
    }
}

export namespace users {
    export interface CreateUserInput {
        email: string
        name: string
        firstName?: string
        lastName?: string
        role?: string
    }

    export interface User {
        id: string
        email: string
        name: string
        firstName: string | null
        lastName: string | null
        role: string
        createdAt: string
        updatedAt: string
    }

    export interface UserListResponse {
        users: User[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Admin: Create a new user.
         */
        public async create(params: CreateUserInput): Promise<User> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/identity/users`, JSON.stringify(params))
            return await resp.json() as User
        }

        /**
         * List all admin users.
         */
        public async list(): Promise<UserListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/identity/users`)
            return await resp.json() as UserListResponse
        }

        /**
         * Admin: Delete a user.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/identity/users/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Admin: Update a user.
         */
        public async update(id: string, params: {
    email?: string
    name?: string
    firstName?: string
    lastName?: string
    role?: string
}): Promise<User> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/identity/users/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as User
        }
    }
}

export namespace analytics {
    export interface ChartItem {
        day: string
        value: number
    }

    export interface ChartResponse {
        items: ChartItem[]
    }

    export interface RecentOrder {
        id: string
        code: string
        customerName: string
        total: number
        state: string
        createdAt: string
    }

    export interface RecentOrdersResponse {
        orders: RecentOrder[]
    }

    export interface SalesStatsResponse {
        current: number
        previous: number
        percentageChange: number
    }

    export interface StatsResponse {
        customers: number
        totalProducts: number
        stockProducts: number
        outOfStock: number
        revenue: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getRecentOrders = this.getRecentOrders.bind(this)
            this.getSalesStats = this.getSalesStats.bind(this)
            this.getWeeklyChart = this.getWeeklyChart.bind(this)
            this.getWeeklyStats = this.getWeeklyStats.bind(this)
        }

        /**
         * Admin: Get recent orders for dashboard.
         */
        public async getRecentOrders(params: {
    limit?: number
}): Promise<RecentOrdersResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/analytics/recent-orders`, undefined, {query})
            return await resp.json() as RecentOrdersResponse
        }

        /**
         * Admin: Get sales stats with percentage change.
         */
        public async getSalesStats(): Promise<SalesStatsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/analytics/sales-stats`)
            return await resp.json() as SalesStatsResponse
        }

        /**
         * Admin: Get weekly chart data.
         */
        public async getWeeklyChart(): Promise<ChartResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/analytics/weekly-chart`)
            return await resp.json() as ChartResponse
        }

        /**
         * Admin: Get weekly dashboard statistics.
         */
        public async getWeeklyStats(): Promise<StatsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/analytics/weekly-stats`)
            return await resp.json() as StatsResponse
        }
    }
}

export namespace banners {
    export interface Banner {
        id: string
        name: string
        position: string
        enabled: boolean
        sortOrder: number
        linkUrl: string | null
        desktopImageId: string | null
        mobileImageId: string | null
        collectionId: string | null
        createdAt: string
        updatedAt: string
        collection?: any
        desktopImage?: any
        mobileImage?: any
    }

    export interface BannerListResponse {
        banners: Banner[]
    }

    export interface CreateBannerInput {
        name: string
        position: string
        enabled?: boolean
        sortOrder?: number
        linkUrl?: string
        desktopImageId?: string
        mobileImageId?: string
        collectionId?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.getByPosition = this.getByPosition.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Admin: Create a new banner.
         */
        public async create(params: CreateBannerInput): Promise<Banner> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/marketing/banners`, JSON.stringify(params))
            return await resp.json() as Banner
        }

        /**
         * Public/Internal endpoint to get banners filtered by position.
         */
        public async getByPosition(position: string, params: {
    enabled?: boolean
}): Promise<BannerListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                enabled: params.enabled === undefined ? undefined : String(params.enabled),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/marketing/banners/position/${encodeURIComponent(position)}`, undefined, {query})
            return await resp.json() as BannerListResponse
        }

        /**
         * Admin: List all banners.
         */
        public async list(): Promise<BannerListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/marketing/banners`)
            return await resp.json() as BannerListResponse
        }

        /**
         * Admin: Delete a banner.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/marketing/banners/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Admin: Update a banner.
         */
        public async update(id: string, params: {
    name?: string
    position?: string
    enabled?: boolean
    sortOrder?: number
    linkUrl?: string
    desktopImageId?: string
    mobileImageId?: string
    collectionId?: string
}): Promise<Banner> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/marketing/banners/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Banner
        }
    }
}

export namespace blog {
    export interface BlogListResponse {
        posts: BlogPost[]
    }

    export interface BlogPost {
        id: string
        slug: string
        title: string
        content: string
        excerpt: string | null
        published: boolean
        assetId: string | null
        createdAt: string
        updatedAt: string
        asset?: any
    }

    export interface CreateBlogInput {
        title: string
        slug: string
        content: string
        excerpt?: string
        published?: boolean
        assetId?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.getBySlug = this.getBySlug.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.togglePublish = this.togglePublish.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Admin: Create a blog post.
         */
        public async create(params: CreateBlogInput): Promise<BlogPost> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/cms/blog`, JSON.stringify(params))
            return await resp.json() as BlogPost
        }

        /**
         * Get a single blog post by ID.
         */
        public async get(id: string): Promise<BlogPost> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/cms/blog/${encodeURIComponent(id)}`)
            return await resp.json() as BlogPost
        }

        /**
         * Get a single blog post by SLUG.
         */
        public async getBySlug(slug: string): Promise<BlogPost> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/cms/blog/slug/${encodeURIComponent(slug)}`)
            return await resp.json() as BlogPost
        }

        /**
         * List blog posts with filters.
         */
        public async list(params: {
    limit?: number
    offset?: number
    published?: boolean
    search?: string
}): Promise<BlogListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:     params.limit === undefined ? undefined : String(params.limit),
                offset:    params.offset === undefined ? undefined : String(params.offset),
                published: params.published === undefined ? undefined : String(params.published),
                search:    params.search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/cms/blog`, undefined, {query})
            return await resp.json() as BlogListResponse
        }

        /**
         * Admin: Delete a blog post.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/cms/blog/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Admin: Toggle publish status.
         */
        public async togglePublish(id: string): Promise<BlogPost> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/cms/blog/${encodeURIComponent(id)}/toggle-publish`)
            return await resp.json() as BlogPost
        }

        /**
         * Admin: Update a blog post.
         */
        public async update(id: string, params: {
    title?: string
    slug?: string
    content?: string
    excerpt?: string
    published?: boolean
    assetId?: string
}): Promise<BlogPost> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/cms/blog/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as BlogPost
        }
    }
}

export namespace campaigns {
    export interface Campaign {
        id: string
        name: string
        slug: string
        type: string
        status: string
        startDate: string | null
        endDate: string | null
        createdAt: string
        updatedAt: string
        metadata?: any
    }

    export interface CampaignListResponse {
        campaigns: Campaign[]
    }

    export interface CreateCampaignInput {
        name: string
        slug: string
        type: string
        status: string
        startDate?: string
        endDate?: string
        metadata?: any
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Admin: Create a campaign.
         */
        public async create(params: CreateCampaignInput): Promise<Campaign> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/campaigns`, JSON.stringify(params))
            return await resp.json() as Campaign
        }

        /**
         * Admin: List all campaigns with filters.
         */
        public async list(params: {
    status?: string
    type?: string
}): Promise<CampaignListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                status: params.status,
                type:   params.type,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/campaigns`, undefined, {query})
            return await resp.json() as CampaignListResponse
        }

        /**
         * Admin: Delete a campaign.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/campaigns/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Admin: Update a campaign.
         */
        public async update(id: string, params: {
    name?: string
    slug?: string
    type?: string
    status?: string
    startDate?: string
    endDate?: string
    metadata?: any
}): Promise<Campaign> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/campaigns/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Campaign
        }
    }
}

export namespace homepage {
    export interface CreateHomepageCollectionInput {
        name: string
        description?: string
        enabled?: boolean
        sortOrder?: number
    }

    export interface HomepageCollection {
        id: string
        name: string
        description: string | null
        enabled: boolean
        sortOrder: number
        createdAt: string
        updatedAt: string
    }

    export interface HomepageCollectionListResponse {
        collections: HomepageCollection[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Admin: Create a homepage collection.
         */
        public async create(params: CreateHomepageCollectionInput): Promise<HomepageCollection> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/cms/homepage-collections`, JSON.stringify(params))
            return await resp.json() as HomepageCollection
        }

        /**
         * Get a single homepage collection by ID.
         */
        public async get(id: string): Promise<HomepageCollection> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/cms/homepage-collections/${encodeURIComponent(id)}`)
            return await resp.json() as HomepageCollection
        }

        /**
         * List all homepage collections ordered by sort order.
         */
        public async list(): Promise<HomepageCollectionListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/cms/homepage-collections`)
            return await resp.json() as HomepageCollectionListResponse
        }

        /**
         * Admin: Delete a homepage collection.
         */
        public async remove(id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/cms/homepage-collections/${encodeURIComponent(id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Admin: Update a homepage collection.
         */
        public async update(id: string, params: {
    name?: string
    description?: string
    enabled?: boolean
    sortOrder?: number
}): Promise<HomepageCollection> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/cms/homepage-collections/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as HomepageCollection
        }
    }
}

export namespace settings {
    export interface PublicSettingsResponse {
        settings: { [key: string]: string }
    }

    export interface SettingsResponse {
        general: { [key: string]: string }
        payments: { [key: string]: string }
        roles: { [key: string]: string }
        shipping: { [key: string]: string }
        taxes: { [key: string]: string }
        policies: { [key: string]: string }
    }

    export interface UpdateSettingsInput {
        general?: { [key: string]: string }
        payments?: { [key: string]: string }
        roles?: { [key: string]: string }
        shipping?: { [key: string]: string }
        taxes?: { [key: string]: string }
        policies?: { [key: string]: string }
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getPublic = this.getPublic.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Get public settings for the storefront.
         */
        public async getPublic(): Promise<PublicSettingsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/settings/public`)
            return await resp.json() as PublicSettingsResponse
        }

        /**
         * Get all settings in a structured format (Admin).
         */
        public async list(): Promise<SettingsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/settings`)
            return await resp.json() as SettingsResponse
        }

        /**
         * Admin: Update settings in bulk.
         */
        public async update(params: UpdateSettingsInput): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/settings`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }
    }
}

export namespace store {
    export interface AssetResponse {
        id: string
        source: string
        name: string
    }

    export interface BannerResponse {
        id: string
        title: string
        subtitle?: string | null
        link?: string | null
        desktopImage: AssetResponse | null
        mobileImage: AssetResponse | null
    }

    export interface BannersResponse {
        banners: BannerResponse[]
    }

    export interface BrandResponse {
        id: string
        name: string
        slug: string
        logo?: AssetResponse | null
    }

    export interface CampaignResponse {
        id: string
        name: string
        status: string
    }

    export interface CampaignsResponse {
        campaigns: CampaignResponse[]
    }

    export interface CartItemInput {
        id?: string
        productId?: string
        quantity: number
    }

    export interface CartValidationResult {
        productId: string
        valid: boolean
        reason?: string
    }

    export interface CollectionResponse {
        id: string
        name: string
        slug: string
        description: string | null
        enabled: boolean
        showInMostShopped: boolean
        sortOrder: number
        asset: AssetResponse | null
        children?: CollectionResponse[]
        parentId?: string | null
    }

    export interface CollectionWithProducts {
        id: string
        title: string
        slug: string
        products: ProductResponse[]
    }

    export interface CollectionsResponse {
        collections: CollectionResponse[]
    }

    export interface HomepageCollectionsResponse {
        collections: CollectionWithProducts[]
    }

    export interface PoliciesResponse {
        policies: { [key: string]: string }
    }

    export interface ProductResponse {
        id: string
        name: string
        slug: string
        description: string | null
        enabled: boolean
        stockOnHand: number
        originalPrice: number | null
        salePrice: number | null
        featuredImage?: string | null
        inStock?: boolean
        brand?: BrandResponse | null
        assets?: any[]
        collections?: any[]
    }

    export interface ProductSearchResponse {
        products: ProductResponse[]
    }

    export interface ProductsResponse {
        data: {
            products: ProductResponse[]
            pagination: {
                total: number
                page: number
                limit: number
                totalPages: number
            }
        }
    }

    export interface ShippingMethodResponse {
        id: string
        name: string
        description?: string | null
        price: number
        enabled: boolean
    }

    export interface ShippingZoneResponse {
        id: string
        name: string
        methodId: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getBanners = this.getBanners.bind(this)
            this.getCampaigns = this.getCampaigns.bind(this)
            this.getCollections = this.getCollections.bind(this)
            this.getHomepageCollections = this.getHomepageCollections.bind(this)
            this.getPolicies = this.getPolicies.bind(this)
            this.getProduct = this.getProduct.bind(this)
            this.getProducts = this.getProducts.bind(this)
            this.getShippingInfo = this.getShippingInfo.bind(this)
            this.search = this.search.bind(this)
            this.validateCart = this.validateCart.bind(this)
        }

        /**
         * Public: Get storefront banners.
         */
        public async getBanners(): Promise<BannersResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/store/banners`)
            return await resp.json() as BannersResponse
        }

        /**
         * Public: Get active marketing campaigns.
         */
        public async getCampaigns(): Promise<CampaignsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/store/campaigns`)
            return await resp.json() as CampaignsResponse
        }

        /**
         * Public: Get collections with hierarchy for the storefront.
         */
        public async getCollections(params: {
    parentId?: string
    featured?: boolean
}): Promise<CollectionsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                featured: params.featured === undefined ? undefined : String(params.featured),
                parentId: params.parentId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/store/collections`, undefined, {query})
            return await resp.json() as CollectionsResponse
        }

        /**
         * Public: Get homepage curated collections.
         */
        public async getHomepageCollections(): Promise<HomepageCollectionsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/store/homepage-collections`)
            return await resp.json() as HomepageCollectionsResponse
        }

        /**
         * Public: Get store policies from settings.
         */
        public async getPolicies(): Promise<PoliciesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/store/policies`)
            return await resp.json() as PoliciesResponse
        }

        /**
         * Public: Get single product by ID or Slug.
         */
        public async getProduct(idOrSlug: string): Promise<{
    success: boolean
    data: ProductResponse
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/store/products/${encodeURIComponent(idOrSlug)}`)
            return await resp.json() as {
    success: boolean
    data: ProductResponse
}
        }

        /**
         * Public: List products with advanced filtering and pagination.
         */
        public async getProducts(params: {
    collectionId?: string
    collection?: string
    search?: string
    minPrice?: number
    maxPrice?: number
    limit?: number
    offset?: number
    page?: number
}): Promise<ProductsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                collection:   params.collection,
                collectionId: params.collectionId,
                limit:        params.limit === undefined ? undefined : String(params.limit),
                maxPrice:     params.maxPrice === undefined ? undefined : String(params.maxPrice),
                minPrice:     params.minPrice === undefined ? undefined : String(params.minPrice),
                offset:       params.offset === undefined ? undefined : String(params.offset),
                page:         params.page === undefined ? undefined : String(params.page),
                search:       params.search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/store/products`, undefined, {query})
            return await resp.json() as ProductsResponse
        }

        /**
         * Public: Get shipping methods and zones.
         */
        public async getShippingInfo(): Promise<{
    methods: ShippingMethodResponse[]
    zones: ShippingZoneResponse[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/store/shipping`)
            return await resp.json() as {
    methods: ShippingMethodResponse[]
    zones: ShippingZoneResponse[]
}
        }

        /**
         * Public: Basic search for dropdowns/autocomplete.
         */
        public async search(params: {
    q: string
}): Promise<ProductSearchResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                q: params.q,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/store/products/search`, undefined, {query})
            return await resp.json() as ProductSearchResponse
        }

        /**
         * Public: Validate cart items for stock and availability.
         */
        public async validateCart(params: {
    items: CartItemInput[]
}): Promise<{
    valid: boolean
    results: CartValidationResult[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/store/cart/validate`, JSON.stringify(params))
            return await resp.json() as {
    valid: boolean
    results: CartValidationResult[]
}
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "mtn9w-Generated-TS-Client (Encore/v1.54.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
